### ISSUE TITLE
Features Ideas + Contributions

### ISSUE THREAD

**Issue by fkS124** [tank-king/scoreunlocked#1]
Hello, fkS here. 

First of all, I want to contribute to the project, and I was wondering if there were any guidelines and conditions to this matter.

Secondly I wanted to share some ideas of new features, that could be interesting for the project. 

- When I first used `scoreunlocked` in my game, every time I posted a new score using `client.post(...)`, the program froze during the process of the function. I fixed it is by using the `threading` python built-in library, and I thought it could be interesting to directly add it in the source code of `scoreunlocked`'s client, with an argument in the `client.post` function that would able/disable this feature.
- A second interesting feature could be to add date and hour of the `client`'s post, in order to see when your high score was lastly achieved. 
- We could also add a `hh:mm:ss` support for posting scores, i.e in a speedrun game, where you rank players according to the duration of their run. 
- Finally we could add unit testing, in order to test if the client's methods works properly.

These are just ideas, and some may be overkill. Though if you feel like any of them could be interesting in the project, I'd be happy to make a contribution for any of them!

**Comment by tank-king** [comment]
Hey! Thanks for the awesome ideas!
Currently there are no particular guidelines to this matter. 

But since your game "Cube's Hidden Dimensions" already uses the leaderboard as it is, I think it would be best to make sure that the same code works well without having to update the game. So for every update to scoreunlocked client (as well as server) we need to ensure some backwards compatibility.

I am replying to the ideas you proposed in the same order:

- You are very right. This is indeed a way to fix it. But I was thinking maybe we could also use an async way of posting the scores. But yes we can do the threading module and add an optional argument to enable or disable this feature. In fact, we could pass the argument in the `__init__` function itself!

- This is an excellent idea! Will definitely add it to the list of updates for version 2!

- I had an idea for this kind of thing, but thought it would be an extra work from the backend because the current system can allow the same kind of behavior. It's upto the developer how they want to represent the scores. 
For example in a race, someone could take 100 seconds and someone could take 101 seconds. So the leaderboard would be sorted in ascending order, and when the score is extracted from the leaderboard, the game could represent them as `00:01:40` and `00:01:41` respectively. 
What are your thoughts on this? Should I make this a separate feature in the backend? Or should I keep it as it is? Or should we add a feature directly inside the client as to how the retreived score will be represented?

- Yes I do have a sample leaderboard to test the scores from the client. We could add more unit testing too.

Once again, Thanks for all the feedback and ideas so far. It would be awesome if you make contributions for them! If you are not interested in implementing certain features, but think that could be useful, please do suggest here - I will do them accordingly :)

**Comment by fkS124** [comment]
I can definitely make a contribution for some of them, but for some others, I'd need some backend access, so I would still need your help!

I'll just do a fork and program the features, though I'm not sure how I can test my new features ? I'll contact you on discord for easier conversation about this. 

Also another idea came to my mind, but it's more for the dev's experience: a way to edit/delete/add some scores directly inside the website, in order to let them do some moderation. An example where it could be useful is for my game, someone complained about a feature not working by putting some username like : "X feature does not work", and it just mess things up in the actual leaderboard.

Lastly, I witnessed some scores' disappearance, still in my game, some scores have disappeared, and I wondered if there was maybe a score count limit for each leader board ? But we can discuss this on discord too.

**Comment by tank-king** [comment]
Yes a discord conversation would be much easier hehe :D 
I have contacted you there :)
